AR=ar -rcs
RM = rm -rf

CC = cc 
CFLAGS= -Wall -Werror -Wextra
INCLUDE = so_long.h


NAME=solomg.a 
SRC=
OBJ_SRC=$(SRC: .c=.o)

all:%(NAME)

$(NAME):$(OBJ_SRC) $(INCLUDE)
	$(AR) $(NAME) $(OBJ_SRC)

%.o:%.c
	$(CC) $(CFLAGS) -c $< -o $@ 

clean:
	$(RM) *.o 

fclean: clean
	$(RM) $(NAME)

re: fclean all 

.PHONY: all clean fclean re 

